[2020-07-15 09:56:59,500] INFO (162) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 09:56:59,517] INFO (162) (server.py:919) Starting worker [162]
[2020-07-15 09:57:22,794] INFO (182) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 09:58:34,899] INFO (216) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 09:58:38,420] INFO (216) (server.py:919) Starting worker [216]
[2020-07-15 09:59:10,622] INFO (249) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 09:59:20,313] INFO (249) (bots.py:31) reload robot rasa-demo version 1.0
[2020-07-15 09:59:20,314] INFO (249) (server.py:919) Starting worker [249]
[2020-07-15 10:53:05,077] INFO (276) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 10:53:05,084] INFO (276) (bots.py:38) reload robot rasa-demo version 1.0
[2020-07-15 10:53:05,085] INFO (276) (server.py:919) Starting worker [276]
[2020-07-15 10:53:54,611] ERROR (276) (handlers.py:176) Exception occurred while handling uri: 'http://127.0.0.1:8080/model/chat'
Traceback (most recent call last):
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /model/chat not found
[2020-07-15 10:53:57,206] ERROR (276) (handlers.py:176) Exception occurred while handling uri: 'http://127.0.0.1:8080/model/chat'
Traceback (most recent call last):
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /model/chat not found
[2020-07-15 10:53:57,867] ERROR (276) (handlers.py:176) Exception occurred while handling uri: 'http://127.0.0.1:8080/model/chat'
Traceback (most recent call last):
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /model/chat not found
[2020-07-15 10:54:29,602] ERROR (276) (handlers.py:176) Exception occurred while handling uri: 'http://127.0.0.1:8080/models/chat'
Traceback (most recent call last):
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/app.py", line 976, in handle_request
    response = await response
  File "/mnt/d/projects/chatbot/chatbot-management_v2/app/model.py", line 107, in post
    bot = request.app.bots[bot_id]  # type:BotManager
KeyError: None
[2020-07-15 10:55:02,745] ERROR (276) (handlers.py:176) Exception occurred while handling uri: 'http://127.0.0.1:8080/models/chat'
Traceback (most recent call last):
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/app.py", line 976, in handle_request
    response = await response
  File "/mnt/d/projects/chatbot/chatbot-management_v2/app/model.py", line 108, in post
    response = await bot.handle_text(req.get("question"))
  File "/mnt/d/projects/chatbot/chatbot-management_v2/core/bots.py", line 48, in handle_text
    response = await self.agent.handle_text(text)
AttributeError: 'NoneType' object has no attribute 'handle_text'
[2020-07-15 10:55:04,787] ERROR (276) (handlers.py:176) Exception occurred while handling uri: 'http://127.0.0.1:8080/models/chat'
Traceback (most recent call last):
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/app.py", line 976, in handle_request
    response = await response
  File "/mnt/d/projects/chatbot/chatbot-management_v2/app/model.py", line 108, in post
    response = await bot.handle_text(req.get("question"))
  File "/mnt/d/projects/chatbot/chatbot-management_v2/core/bots.py", line 48, in handle_text
    response = await self.agent.handle_text(text)
AttributeError: 'NoneType' object has no attribute 'handle_text'
[2020-07-15 10:56:05,511] ERROR (276) (handlers.py:176) Exception occurred while handling uri: 'http://127.0.0.1:8080/models/chat'
Traceback (most recent call last):
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/app.py", line 976, in handle_request
    response = await response
  File "/mnt/d/projects/chatbot/chatbot-management_v2/app/model.py", line 108, in post
    response = await bot.handle_text(req.get("question"))
  File "/mnt/d/projects/chatbot/chatbot-management_v2/core/bots.py", line 48, in handle_text
    response = await self.agent.handle_text(text)
AttributeError: 'NoneType' object has no attribute 'handle_text'
[2020-07-15 10:56:50,834] ERROR (276) (handlers.py:176) Exception occurred while handling uri: 'http://127.0.0.1:8080/models/chat'
Traceback (most recent call last):
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/app.py", line 976, in handle_request
    response = await response
  File "/mnt/d/projects/chatbot/chatbot-management_v2/app/model.py", line 108, in post
    response = await bot.handle_text(req.get("question"))
  File "/mnt/d/projects/chatbot/chatbot-management_v2/core/bots.py", line 48, in handle_text
    response = await self.agent.handle_text(text)
AttributeError: 'NoneType' object has no attribute 'handle_text'
[2020-07-15 10:57:09,566] INFO (309) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 10:57:09,572] INFO (309) (bots.py:38) reload robot rasa-demo version 1.0
[2020-07-15 10:57:09,573] INFO (309) (server.py:919) Starting worker [309]
[2020-07-15 10:58:02,882] INFO (341) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 10:59:39,101] INFO (341) (bots.py:38) reload robot rasa-demo version 1.0
[2020-07-15 10:59:39,103] INFO (341) (server.py:919) Starting worker [341]
[2020-07-15 10:59:44,480] INFO (413) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 11:00:07,000] INFO (413) (bots.py:38) reload robot rasa-demo version 1.0
[2020-07-15 11:00:07,002] INFO (413) (server.py:919) Starting worker [413]
[2020-07-15 11:00:52,111] INFO (436) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 11:02:17,255] INFO (436) (bots.py:38) reload robot rasa-demo version 1.0
[2020-07-15 11:02:17,257] INFO (436) (server.py:919) Starting worker [436]
[2020-07-15 11:02:21,131] INFO (457) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 11:02:29,430] INFO (457) (bots.py:38) reload robot rasa-demo version 1.0
[2020-07-15 11:02:29,431] INFO (457) (server.py:919) Starting worker [457]
[2020-07-15 11:03:30,315] INFO (480) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 11:03:33,999] INFO (480) (bots.py:38) reload robot rasa-demo version 0.1
[2020-07-15 11:03:34,001] INFO (480) (server.py:919) Starting worker [480]
[2020-07-15 11:03:43,885] INFO (501) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 11:04:58,585] INFO (519) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 11:05:27,926] INFO (519) (bots.py:38) reload robot rasa-demo version 0.1
[2020-07-15 11:05:27,928] INFO (519) (server.py:919) Starting worker [519]
[2020-07-15 11:07:46,140] ERROR (519) (handlers.py:176) Exception occurred while handling uri: 'http://127.0.0.1:8080/model/parse'
Traceback (most recent call last):
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /model/parse not found
[2020-07-15 11:11:03,300] ERROR (519) (handlers.py:176) Exception occurred while handling uri: 'http://127.0.0.1:8080/model/train'
Traceback (most recent call last):
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /model/train not found
[2020-07-15 11:17:10,862] INFO (519) (bots.py:38) reload robot rasa-demo version 0.1
[2020-07-15 11:19:04,695] INFO (3516) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 11:19:28,616] INFO (3531) (bots.py:38) reload robot rasa-demo version 0.1
[2020-07-15 11:19:28,616] INFO (3532) (bots.py:38) reload robot rasa-demo version 0.1
[2020-07-15 11:19:28,618] INFO (3538) (bots.py:38) reload robot rasa-demo version 0.1
[2020-07-15 11:19:28,622] INFO (3535) (bots.py:38) reload robot rasa-demo version 0.1
[2020-07-15 11:19:28,627] INFO (3531) (server.py:919) Starting worker [3531]
[2020-07-15 11:19:28,627] INFO (3535) (server.py:919) Starting worker [3535]
[2020-07-15 11:19:28,627] INFO (3538) (server.py:919) Starting worker [3538]
[2020-07-15 11:19:28,627] INFO (3532) (server.py:919) Starting worker [3532]
[2020-07-15 11:28:19,516] INFO (9130) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 11:30:46,889] INFO (9145) (bots.py:38) reload robot rasa-demo version 0.1
[2020-07-15 11:31:58,214] INFO (9145) (server.py:919) Starting worker [9145]
[2020-07-15 11:32:19,140] INFO (9151) (bots.py:38) reload robot rasa-demo version 0.1
[2020-07-15 11:32:19,141] INFO (9151) (server.py:919) Starting worker [9151]
[2020-07-15 11:32:19,164] INFO (9148) (bots.py:38) reload robot rasa-demo version 0.1
[2020-07-15 11:32:19,165] INFO (9148) (server.py:919) Starting worker [9148]
[2020-07-15 11:32:19,199] INFO (9154) (bots.py:38) reload robot rasa-demo version 0.1
[2020-07-15 11:32:19,200] INFO (9154) (server.py:919) Starting worker [9154]
[2020-07-15 11:50:15,546] INFO (14874) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 11:50:41,594] INFO (14895) (bots.py:38) reload robot rasa-demo version 0.1
[2020-07-15 11:50:41,595] INFO (14895) (server.py:919) Starting worker [14895]
[2020-07-15 11:50:41,595] INFO (14889) (bots.py:38) reload robot rasa-demo version 0.1
[2020-07-15 11:50:41,595] INFO (14892) (bots.py:38) reload robot rasa-demo version 0.1
[2020-07-15 11:50:41,596] INFO (14889) (server.py:919) Starting worker [14889]
[2020-07-15 11:50:41,596] INFO (14892) (server.py:919) Starting worker [14892]
[2020-07-15 11:50:41,599] INFO (14898) (bots.py:38) reload robot rasa-demo version 0.1
[2020-07-15 11:50:41,600] INFO (14898) (server.py:919) Starting worker [14898]
[2020-07-15 12:44:00,426] INFO (20526) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 12:45:43,872] INFO (20550) (bots.py:63) reload robot rasa-demo version 0.1
[2020-07-15 12:45:43,872] INFO (20544) (bots.py:63) reload robot rasa-demo version 0.1
[2020-07-15 12:45:43,872] INFO (20547) (bots.py:63) reload robot rasa-demo version 0.1
[2020-07-15 12:45:43,873] INFO (20547) (server.py:919) Starting worker [20547]
[2020-07-15 12:45:43,873] INFO (20550) (server.py:919) Starting worker [20550]
[2020-07-15 12:45:43,873] ERROR (20544) (server.py:897) Unable to start server
Traceback (most recent call last):
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/server.py", line 895, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1717, in create_server
  File "uvloop/loop.pyx", line 1714, in uvloop.loop.Loop.create_server
  File "uvloop/handles/streamserver.pyx", line 58, in uvloop.loop.UVStreamServer.listen
  File "uvloop/handles/streamserver.pyx", line 95, in uvloop.loop.UVStreamServer._fatal_error
OSError: [Errno 107] Transport endpoint is not connected
[2020-07-15 12:45:43,883] INFO (20541) (bots.py:63) reload robot rasa-demo version 0.1
[2020-07-15 12:45:43,884] INFO (20541) (server.py:919) Starting worker [20541]
[2020-07-15 13:56:56,255] INFO (26166) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 13:57:49,047] INFO (26184) (bots.py:63) reload robot rasa-demo version 0.1
[2020-07-15 13:57:49,047] INFO (26181) (bots.py:63) reload robot rasa-demo version 0.1
[2020-07-15 13:57:49,048] INFO (26184) (server.py:919) Starting worker [26184]
[2020-07-15 13:57:49,048] INFO (26181) (server.py:919) Starting worker [26181]
[2020-07-15 13:57:49,058] INFO (26187) (bots.py:63) reload robot rasa-demo version 0.1
[2020-07-15 13:57:49,058] INFO (26190) (bots.py:63) reload robot rasa-demo version 0.1
[2020-07-15 13:57:49,060] INFO (26190) (server.py:919) Starting worker [26190]
[2020-07-15 13:57:49,060] INFO (26187) (server.py:919) Starting worker [26187]
[2020-07-15 13:58:00,586] INFO (31772) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 13:58:48,562] INFO (31787) (bots.py:63) reload robot rasa-demo version 0.1
[2020-07-15 13:58:48,563] INFO (31787) (server.py:919) Starting worker [31787]
[2020-07-15 13:58:48,593] INFO (31790) (bots.py:63) reload robot rasa-demo version 0.1
[2020-07-15 13:58:48,594] INFO (31790) (server.py:919) Starting worker [31790]
[2020-07-15 13:58:48,650] INFO (31796) (bots.py:63) reload robot rasa-demo version 0.1
[2020-07-15 13:58:48,651] INFO (31796) (server.py:919) Starting worker [31796]
[2020-07-15 13:58:48,694] INFO (31793) (bots.py:63) reload robot rasa-demo version 0.1
[2020-07-15 13:58:48,695] INFO (31793) (server.py:919) Starting worker [31793]
[2020-07-15 13:59:45,754] INFO (4660) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 14:01:03,601] INFO (4713) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 14:03:37,225] INFO (4754) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 14:24:34,462] INFO (4772) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:24:34,463] INFO (4772) (server.py:919) Starting worker [4772]
[2020-07-15 14:24:34,523] INFO (4769) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:24:34,523] INFO (4769) (server.py:919) Starting worker [4769]
[2020-07-15 14:24:34,576] INFO (4778) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:24:34,577] INFO (4778) (server.py:919) Starting worker [4778]
[2020-07-15 14:24:34,726] INFO (4775) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:24:34,727] INFO (4775) (server.py:919) Starting worker [4775]
[2020-07-15 14:25:51,396] INFO (10406) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 14:26:14,606] INFO (10427) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:26:14,607] INFO (10427) (server.py:919) Starting worker [10427]
[2020-07-15 14:26:14,640] INFO (10430) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:26:14,641] INFO (10430) (server.py:919) Starting worker [10430]
[2020-07-15 14:26:14,644] INFO (10421) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:26:14,645] INFO (10421) (server.py:919) Starting worker [10421]
[2020-07-15 14:26:14,686] INFO (10424) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:26:14,687] INFO (10424) (server.py:919) Starting worker [10424]
[2020-07-15 14:29:08,918] INFO (16065) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 14:29:31,727] INFO (16065) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:29:31,728] INFO (16065) (server.py:919) Starting worker [16065]
[2020-07-15 14:35:12,372] INFO (17518) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 14:35:35,435] INFO (17518) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:35:35,436] INFO (17518) (server.py:919) Starting worker [17518]
[2020-07-15 14:37:56,078] INFO (18959) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 14:38:17,024] INFO (18959) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:38:17,025] INFO (18959) (server.py:919) Starting worker [18959]
[2020-07-15 14:38:56,000] INFO (20439) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 14:39:17,589] INFO (20439) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:39:17,590] INFO (20439) (server.py:919) Starting worker [20439]
[2020-07-15 14:46:32,435] INFO (21871) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 14:46:55,979] INFO (21892) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:46:55,980] INFO (21892) (server.py:919) Starting worker [21892]
[2020-07-15 14:46:56,023] INFO (21895) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:46:56,024] INFO (21895) (server.py:919) Starting worker [21895]
[2020-07-15 14:46:56,079] INFO (21886) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:46:56,080] INFO (21886) (server.py:919) Starting worker [21886]
[2020-07-15 14:46:56,121] INFO (21889) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 14:46:56,122] INFO (21889) (server.py:919) Starting worker [21889]
[2020-07-15 15:49:11,105] INFO (27681) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 15:49:35,857] INFO (27702) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 15:49:35,857] INFO (27699) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 15:49:35,858] INFO (27702) (server.py:919) Starting worker [27702]
[2020-07-15 15:49:35,858] INFO (27699) (server.py:919) Starting worker [27699]
[2020-07-15 15:49:35,880] INFO (27705) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 15:49:35,881] INFO (27705) (server.py:919) Starting worker [27705]
[2020-07-15 15:49:35,917] INFO (27696) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 15:49:35,918] INFO (27696) (server.py:919) Starting worker [27696]
[2020-07-15 15:52:04,562] INFO (570) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 15:52:28,199] INFO (588) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 15:52:28,200] INFO (588) (server.py:919) Starting worker [588]
[2020-07-15 15:52:28,227] INFO (594) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 15:52:28,228] INFO (594) (server.py:919) Starting worker [594]
[2020-07-15 15:52:28,301] INFO (591) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 15:52:28,302] INFO (591) (server.py:919) Starting worker [591]
[2020-07-15 15:52:28,387] INFO (585) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 15:52:28,388] INFO (585) (server.py:919) Starting worker [585]
[2020-07-15 17:04:00,034] INFO (7) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:04:21,102] INFO (7) (app.py:1177) Server Stopped
[2020-07-15 17:05:28,620] INFO (7) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:05:28,721] INFO (7) (app.py:1177) Server Stopped
[2020-07-15 17:05:42,948] INFO (40) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:05:43,006] INFO (40) (app.py:1177) Server Stopped
[2020-07-15 17:07:50,233] INFO (7) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:07:50,298] INFO (7) (app.py:1177) Server Stopped
[2020-07-15 17:08:20,525] INFO (7) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:08:20,584] INFO (7) (app.py:1177) Server Stopped
[2020-07-15 17:09:32,408] INFO (7) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:09:32,471] INFO (7) (app.py:1177) Server Stopped
[2020-07-15 17:10:47,996] INFO (7) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:10:48,178] INFO (7) (app.py:1177) Server Stopped
[2020-07-15 17:11:14,497] INFO (7) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:12:03,083] INFO (7) (app.py:1177) Server Stopped
[2020-07-15 17:12:38,775] INFO (7) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:12:46,128] INFO (7) (app.py:1177) Server Stopped
[2020-07-15 17:16:17,080] INFO (95) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:16:31,881] INFO (95) (app.py:1177) Server Stopped
[2020-07-15 17:17:17,911] INFO (7) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:17:27,348] INFO (7) (app.py:1177) Server Stopped
[2020-07-15 17:18:38,694] INFO (7) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:18:38,872] INFO (7) (app.py:1177) Server Stopped
[2020-07-15 17:19:04,709] INFO (15) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:19:04,902] INFO (15) (app.py:1177) Server Stopped
[2020-07-15 17:20:31,205] INFO (7) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:20:31,390] INFO (7) (app.py:1177) Server Stopped
[2020-07-15 17:22:48,064] INFO (44) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:22:48,271] INFO (44) (app.py:1177) Server Stopped
[2020-07-15 17:23:54,150] INFO (80) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:23:54,340] INFO (80) (app.py:1177) Server Stopped
[2020-07-15 17:24:10,385] INFO (116) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:24:10,561] INFO (116) (app.py:1177) Server Stopped
[2020-07-15 17:32:03,158] INFO (7) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:32:27,460] INFO (19) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:32:27,460] INFO (21) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:32:27,460] INFO (20) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:32:27,460] INFO (22) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:32:27,460] INFO (19) (server.py:919) Starting worker [19]
[2020-07-15 17:32:27,460] ERROR (22) (server.py:897) Unable to start server
Traceback (most recent call last):
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/server.py", line 895, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1717, in create_server
  File "uvloop/loop.pyx", line 1714, in uvloop.loop.Loop.create_server
  File "uvloop/handles/streamserver.pyx", line 58, in uvloop.loop.UVStreamServer.listen
  File "uvloop/handles/streamserver.pyx", line 95, in uvloop.loop.UVStreamServer._fatal_error
OSError: [Errno 107] Transport endpoint is not connected
[2020-07-15 17:32:27,460] ERROR (20) (server.py:897) Unable to start server
Traceback (most recent call last):
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/server.py", line 895, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1717, in create_server
  File "uvloop/loop.pyx", line 1714, in uvloop.loop.Loop.create_server
  File "uvloop/handles/streamserver.pyx", line 58, in uvloop.loop.UVStreamServer.listen
  File "uvloop/handles/streamserver.pyx", line 95, in uvloop.loop.UVStreamServer._fatal_error
OSError: [Errno 107] Transport endpoint is not connected
[2020-07-15 17:32:27,460] ERROR (21) (server.py:897) Unable to start server
Traceback (most recent call last):
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/server.py", line 895, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1717, in create_server
  File "uvloop/loop.pyx", line 1714, in uvloop.loop.Loop.create_server
  File "uvloop/handles/streamserver.pyx", line 58, in uvloop.loop.UVStreamServer.listen
  File "uvloop/handles/streamserver.pyx", line 95, in uvloop.loop.UVStreamServer._fatal_error
OSError: [Errno 107] Transport endpoint is not connected
[2020-07-15 17:39:28,352] INFO (81) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:39:28,465] INFO (81) (app.py:1177) Server Stopped
[2020-07-15 17:43:21,578] INFO (146) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:43:49,652] INFO (164) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:43:49,652] INFO (170) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:43:49,652] INFO (161) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:43:49,652] INFO (167) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:43:49,653] INFO (164) (server.py:919) Starting worker [164]
[2020-07-15 17:43:49,653] INFO (167) (server.py:919) Starting worker [167]
[2020-07-15 17:43:49,653] INFO (161) (server.py:919) Starting worker [161]
[2020-07-15 17:43:49,652] ERROR (170) (server.py:897) Unable to start server
Traceback (most recent call last):
  File "/home/wireless/Envs/chatbot-management-v2/lib/python3.6/site-packages/sanic/server.py", line 895, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1717, in create_server
  File "uvloop/loop.pyx", line 1714, in uvloop.loop.Loop.create_server
  File "uvloop/handles/streamserver.pyx", line 58, in uvloop.loop.UVStreamServer.listen
  File "uvloop/handles/streamserver.pyx", line 95, in uvloop.loop.UVStreamServer._fatal_error
OSError: [Errno 107] Transport endpoint is not connected
[2020-07-15 17:48:58,452] INFO (5828) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:49:23,580] INFO (5843) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:49:23,581] INFO (5843) (server.py:919) Starting worker [5843]
[2020-07-15 17:49:23,740] INFO (5849) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:49:23,740] INFO (5846) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:49:23,741] INFO (5849) (server.py:919) Starting worker [5849]
[2020-07-15 17:49:23,741] INFO (5846) (server.py:919) Starting worker [5846]
[2020-07-15 17:49:23,741] INFO (5852) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:49:23,742] INFO (5852) (server.py:919) Starting worker [5852]
[2020-07-15 17:55:34,631] INFO (11528) (app.py:1433) Goin' Fast @ http://0.0.0.0:8080
[2020-07-15 17:55:59,057] INFO (11543) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:55:59,058] INFO (11543) (server.py:919) Starting worker [11543]
[2020-07-15 17:55:59,219] INFO (11552) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:55:59,220] INFO (11552) (server.py:919) Starting worker [11552]
[2020-07-15 17:55:59,223] INFO (11546) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:55:59,224] INFO (11546) (server.py:919) Starting worker [11546]
[2020-07-15 17:55:59,228] INFO (11549) (bots.py:65) reload robot rasa-demo version 0.1
[2020-07-15 17:55:59,229] INFO (11549) (server.py:919) Starting worker [11549]
